package com.redsamurai.model.client;

import com.redsamurai.model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 21 09:19:34 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void cleanTable() {
        Object _ret = this.riInvokeExportedMethod(this,"cleanTable",null,null);
        return;
    }

    public void populateTable() {
        Object _ret = this.riInvokeExportedMethod(this,"populateTable",null,null);
        return;
    }
}
