package com.redsamurai.model;


import com.redsamurai.model.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 16:17:24 EEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl)findViewObject("RegionsView1");
    }

    public void populateTable() {

        for (int i = 1; i < 10000; i ++) {

          Row row = getRegionsView1().createRow();
          row.setAttribute("RegionId", 100 + i);  
          row.setAttribute("RegionName", "REGION_NAME" + i);  
          getRegionsView1().insertRow(row);
          getDBTransaction().commit();  
        }

    }


    /**
     * removes all previously inserted records using populateTable() method
     */
    public void cleanTable() {
        ViewCriteria vc = getRegionsView1().getViewCriteria("RegionsViewCriteria");
        getRegionsView1().applyViewCriteria(vc);
        getRegionsView1().executeQuery();
        RowSetIterator rsi = getRegionsView1().createRowSetIterator(null);
        while(rsi.hasNext())  {
        
            rsi.next().remove();
        }
        getDBTransaction().commit();  
        
        
        rsi.closeRowSetIterator();
        
    }

    }

