package com.redsamurai.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 21 09:19:34 EEST 2012
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void populateTable();

    void cleanTable();
}
